<!Doctype HTML>
<html>
    <head>
        <title>Sindrenj.net <?php echo (isset($pageTitle) ? "- " . $pageTitle : ''); //harsh!?> </title>
        {{ stylesheet_link("css/default.css") }}
        <meta charset="utf-8">
    </head>
    <body>
        <div id="wrapper">
            <header>
                <h1><a href="/HomePage/">Sindrenj.net</a></h1>
            </header>
            <div id="mainContent">
                <nav>
                   <ul id="navigation">
                     <li><a href="http://localhost/HomePage">Home</a></li>
                     <li><a href="/HomePage/Index/About">About me<a></li>
                     <li><a href="/HomePage/Projects/">Projects</a></li>
                     <li><a href="/HomePage/Users/login">Sign in</a></li>
                     <li><a href="/HomePage/Posts/" class="navAdmin">Create</a></li>
                   </ul>
                </nav>  
                <?php echo $this->getContent() ?>
            </div>
            <!-- "Push" is simply added to enable a sticky footer -->
            <div id="push"></div>
        </div>
        <footer>
            <p id="footerContentLeft">Sindrenj.net - Personal homepage for Sindre Njøsen</p><a href="http://phalconphp.com" id="footerLinkRight">powered by PhalconPHP</a>
        </footer>
     </body>
</html>