<section id="mainCreatePost">
    <h2>Edit</h2>
    <?php 
       use Phalcon\Tag; 
       //Create the form
       echo Tag::form(array("Posts/create", "method" => "post"));
    ?>
        <label>Headline</label><br>
        <input type="text" id="txtHeadline" name="txtHeadline" value="{{ post.headline }}"><br>
        <label>Content</label><br>
        <textarea id="txtContent" name="txtContent">
        <?php echo $post->content ?>
        </textarea><br>
        <input type="submit" value="Edit" id="btnCreate">
    </form>
</section>
<aside id="right">
    <h2>Posts</h2>
    <ul>
        <?php foreach($posts as $post) { 
            echo "<li><a href='/HomePage/posts/edit/" . $post->id . "'>" . $post->headline . "</a></li>";
        } ?>
    </ul>
</aside>
