<h2>Create a new post!</h2>
<?php 
    use Phalcon\Tag; 
    //Create the form
    echo Tag::form(array("Posts/create", "method" => "post"));
?>
        <label>Headline</label><br>
        <input type="text" id="txtHeadline" name="txtHeadline"><br>
        <label>Content</label><br>
        <textarea id="txtContent" name="txtContent">
            
        </textarea><br>
        <input type="submit" value="Create">
    </form>

