<aside id="right">
    <h2>Posts</h2>
    <ul>
        <li><a href="#">Blogginnleggnummer1</a></li>
        <li><a href="#">Blogginnleggnummer2</a></li>
        <li><a href="#">Blogginnleggnummer3</a></li>
    </ul>
    <h2>Categories</h2>
    <ul>
        <li><a href="#">Kategorinummer1</a></li>
        <li><a href="#">Kategorinummer2</a></li>
        <li><a href="#">Kategorinummer3</a></li>
    </ul>
    <h2>Tutorials</h2>
    <ul>
        <li><a href="#">Kategorinummer1</a></li>
        <li><a href="#">Kategorinummer2</a></li>
        <li><a href="#">Kategorinummer3</a></li>
    </ul>
    <h2>Projects</h2>
    <ul>
        <li><a href="#">Vennernummer1</a></li>
        <li><a href="#">Vennernummer2</a></li>
        <li><a href="#">Vennernummer3</a></li>
    </ul>
</aside>
<section id="main">
    <?php foreach ($page->items as $post) { ?>
        <article>
            <h3><?php echo $post->headline; ?></h3>
            <?php echo $post->content_front; ?>
            <a href="/HomePage/posts/view/<?= $post->id ?>" class="readMoreLink">more..</a>
        </article>
    <?php } ?>
</section>
