
    <?php foreach($projects as $project) { ?>
    <article>
        <h2><?php echo $project->name ?></h2>
        <img class="projectImage" src="/HomePage/images/upload/projectHomePage.png" />
        <ul>
            <b>Key features:</b>
            <li>- Feature ..</li>
            <li>- Feature ..</li>
            <li>- Feature ..</li>
        </ul>
        <p><?php echo $project->description ?></p>
    </article>
    <?php } ?>
