<h3>Sign up using this form</h3>
<form name="frmRegister" method="POST" action="Create">
 <p>
    <label for="firstname">Firstname</label>
    <input type="text" name="firstname"/>
 </p>
 <p>
    <label for="lastname">Lastname</label>
    <input type="text" name="lastname"/>
 </p>
 <p>
    <label for="lastname">Password</label>
    <input type="password" name="password"/>
 </p>
 <p>
    <label for="email">E-Mail</label>
    <input type="email" name="email"/>
 </p>
 <input type="submit" name="btnSubmit" value="Register">
</form>
